### ISSUE TITLE
Add support for `node-gyp-build`

### ISSUE THREAD

**Issue by guybedford** [zeit/node-file-trace#1]
See https://www.npmjs.com/package/node-gyp-build.

**Comment by styfle** [comment]
@guybedford Looks like `node-gyp-build` is used here: https://github.com/zeit/node-file-trace/blob/d7410632a5aadc1c461b59d39ce761dfbb95cf48/src/analyze.js#L99-L101

Anything else need to be implemented to support `node-gyp-build` or can we close this?

**Comment by guybedford** [comment]
Yes this was added with the Node.js 12 CI fixes.
