### ISSUE TITLE
Error: Cannot find module when file has `.tsx` extension

### ISSUE THREAD

**Issue by styfle** [zeit/node-file-trace#10]
Deploying [this repo](https://github.com/styfle/react-server-example-tsx) fails with error `Cannot find module './components/app'`

I haven't investigated if this is a bug in the TS compilation from the `@now/node` builder or the `node-file-trace` but wanted to log this issue before I forget.

**Comment by styfle** [comment]
@guybedford PR #10 did not fix this error. It still fails in the same way.

**Comment by guybedford** [comment]
As mentioned in that PR we likely need to add the tax extension to the
typescript resolver here as well.

**Comment by styfle** [comment]
This is the highest priority issue - Let's fix this ASAP.

@guybedford Can you work on this?

**Comment by guybedford** [comment]
Let's track this in https://github.com/zeit/now-builders/pull/760.

**Comment by styfle** [comment]
Thanks, this is fixed in `@now/node@canary`.
