### ISSUE TITLE
Add support for `@prisma/sdk`

### ISSUE THREAD

**Issue by styfle** [zeit/node-file-trace#104]
Similar to #28 there is a binary file that is dynamically generated that must be included.

Steps to reproduce:

1. `yarn add @prisma/sdk`
2. Create a file with:

```js
const { getDMMF } = require('@prisma/sdk')

const defaultSchema = `
generator photon {
  provider = "photonjs"
}

model Test {
  id                 String           @default(cuid()) @id
}
`;

getDMMF({ datamodel: defaultSchema})
  .then(() => console.log('success')
  .catch(() => console.log('error')
```

Fails with error `Could not find query-engine binary`.

## Solution

Special case `@prisma/sdk/dist/engineCommands.js` to include `@prisma/sdk/query-engine-*`.

**Comment by styfle** [comment]
@timsuchanek Can the binaries be generated to a `runtime` directory instead similar to `@prisma/photon` in #28?

**Comment by timsuchanek** [comment]
@styfle yes, we could use a `runtime` directory which could be code generated, however, I would prefer to keep the sdk generation free.
I'll probably just add code annotations to the sdk to refer to the possible engine files.

**Comment by timsuchanek** [comment]
From my current knowledge, I would have to generate out a lot of path.join statements, like so:
```ts
path.join(__dirname, '../query-engine-darwin')
path.join(__dirname, '../query-engine-windows')
```
Is there a way to use a wildcard to tell `node-file-trace` that all those files should be copied like:
```ts
/** node-file-trace-include:"../query-engine-*" **/
```

**Comment by styfle** [comment]
There is no special annotation, however it should work if you follow one of these patterns:

- https://github.com/zeit/node-file-trace/blob/master/test/unit/wildcard/input.js
- https://github.com/zeit/node-file-trace/blob/master/test/unit/wildcard2/input.js
- https://github.com/zeit/node-file-trace/blob/master/test/unit/wildcard3/input.js
- https://github.com/zeit/node-file-trace/blob/master/test/unit/wildcard-require/input.js

**Comment by williamluke4** [comment]
I'll give this a go tomorrow

**Comment by williamluke4** [comment]
I've had no luck

**Comment by timsuchanek** [comment]
Done in the latest alpha version of `@prisma/sdk` :)
The issue can be closed.

**Comment by styfle** [comment]
Confirmed, this works with `@prisma/sdk@2.0.0-alpha.909`.

**Comment by williamluke4** [comment]
Thanks Guys :)
