### ISSUE TITLE
Add support for `bull`

### ISSUE THREAD

**Issue by styfle** [zeit/node-file-trace#35]
Example integration test:

```js
const Queue = require('bull');
const host = 'redis123.cloud.redislabs.com';
const port = 10883;
const password = 'abc123pswrd';
const pdfQueue = new Queue('pdf transcoding', { redis: { port, host, password }});

pdfQueue.process(function(job, done) {
    job.progress(42);
    job.progress(99);
    done();
    pdfQueue.close();
});

pdfQueue.add({ pdf: 'http://example.com/file.pdf' });
```

This currently fails to find any files in `node_modules/bull/**` like I would expect and fails with the following error:

```
TypeError: queue.client.updateDelaySet is not a function
```

**Comment by guybedford** [comment]
An interesting thing to check with failures like this would be to compare
against ncc - will distinguish the easy bugs from the harder ones at least!

**Comment by styfle** [comment]
@guybedford Good point!

It also fails when using `ncc` with the following error:

```
TypeError: client.addJob is not a function
```
