### ISSUE TITLE
`phantomjs-prebuilt` does not work

### ISSUE THREAD

**Issue by TooTallNate** [zeit/node-file-trace#44]
Attached is a zip for a project that uses `phantomjs-prebuilt`, and results in an error such as:

```
Error: spawn /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
```

Reproducible in `now dev` as well. When I take a look at the file path "node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs" the file is indeed _not_ there, so perhaps the detection mechanism isn't including the binary into the output results.

[odc.zip](https://github.com/zeit/node-file-trace/files/3499332/odc.zip)

**Comment by styfle** [comment]
This packages is 70MB so I doubt it will fit in a lambda, even if we could trace it properly https://packagephobia.now.sh/result?p=phantomjs-prebuilt

**Comment by jaruba** [comment]
I am still unable to use `phantomjs-prebuilt` with Now.sh.

Here are the errors:
```
[31merror[39m: Could not spawn [/var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs] executable. Please make sure phantomjs is installed correctly.
[31merror[39m: undefined {"errno":"ENOENT","code":"ENOENT","syscall":"spawn /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs","path":"/var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs","spawnargs":["--local-url-access=false","/var/task/node_modules/phantom/dist/shim/index.js"]}
RequestId: 1ab2f546-b7e6-48d0-9d88-a4645a55d71b Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

And a simplistic test case:
[test-phantomjs-serverless.zip](https://github.com/zeit/node-file-trace/files/4225759/test-phantomjs-serverless.zip)

**Comment by nandorojo** [comment]
Is there a fix for this? I'm still getting this error.

**Comment by styfle** [comment]
This looks like a bug in `markdown-pdf`.

`nft print index.js` shows the following dependencies are missing:

```
Error: Failed to resolve dependency system:
Cannot find module 'system' loaded from example/node_modules/markdown-pdf/phantom/render.js
Error: Failed to resolve dependency webpage:
Cannot find module 'webpage' loaded from example/node_modules/markdown-pdf/phantom/render.js
```

Try running `yarn install system webpage` to make sure those dependencies are installed since markdown-pdf forgot to add to `dependencies` in [package.json](https://cdn.jsdelivr.net/npm/markdown-pdf@10.0.0/package.json) even though they are required in [render.js](https://cdn.jsdelivr.net/npm/markdown-pdf@10.0.0/phantom/render.js).

I suggest creating an issue in the `markdown-pdf` repo.

**Comment by JuanM04** [comment]
I happens to me with `html-pdf`

**Comment by alesanchezr** [comment]
Me too!! @JuanM04 any luck?? I'm trying to fix this with `html-pdf`.

It only happens in vercel server, it works perfect on the development server.

```
Error creating PDF Error: spawn ./node_modules/phantomjs/bin/phantomjs ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ./node_modules/phantomjs/bin/phantomjs',
  path: './node_modules/phantomjs/bin/phantomjs',
  spawnargs: [ '/var/task/node_modules/html-pdf/lib/scripts/pdf_a4_portrait.js' ]
}
```

**Comment by JuanM04** [comment]
https://github.com/marcbachmann/node-html-pdf/issues/586#issuecomment-673725644

**Comment by amaurym** [comment]
I'm not sure why this is closed, I'm still facing this issue with `markdown-pdf`.

**Comment by tthiagopereira** [comment]
I'm having the same problem using HTML-PDF two days trying to solve this and nothing

**Comment by CogenEnergy** [comment]
same problem here in vercel

**Comment by ibockowsky** [comment]
Problem still exists

**Comment by RobzLegz** [comment]
Same thing here.

Issue still exists

```
Error: spawn /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
  path: '/var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
  spawnargs: [
    '--local-url-access=false',
    '/var/task/node_modules/html-pdf/lib/scripts/pdf_a4_portrait.js'
  ]
}
2022-08-17T19:23:41.824Z	92d59458-9985-4a35-b013-aeeca8e85b44	ERROR	Uncaught Exception 	{"errorType":"TypeError","errorMessage":"Cannot read properties of undefined (reading 'pipe')","stack":["TypeError: Cannot read properties of undefined (reading 'pipe')","    at /var/task/.next/server/chunks/1950.js:861:16","    at /var/task/node_modules/html-pdf/lib/pdf.js:60:21","    at respond (/var/task/node_modules/html-pdf/lib/pdf.js:141:14)","    at ChildProcess.onError (/var/task/node_modules/html-pdf/lib/pdf.js:149:46)","    at ChildProcess.emit (node:events:527:28)","    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)","    at onErrorNT (node:internal/child_process:478:16)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]}
Unknown application error occurred
```

**Comment by eg-delacruz** [comment]
> Same thing here.
> 
> Issue still exists
> 
> ```
> Error: spawn /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
>     at onErrorNT (node:internal/child_process:478:16)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'spawn /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
>   path: '/var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
>   spawnargs: [
>     '--local-url-access=false',
>     '/var/task/node_modules/html-pdf/lib/scripts/pdf_a4_portrait.js'
>   ]
> }
> 2022-08-17T19:23:41.824Z	92d59458-9985-4a35-b013-aeeca8e85b44	ERROR	Uncaught Exception 	{"errorType":"TypeError","errorMessage":"Cannot read properties of undefined (reading 'pipe')","stack":["TypeError: Cannot read properties of undefined (reading 'pipe')","    at /var/task/.next/server/chunks/1950.js:861:16","    at /var/task/node_modules/html-pdf/lib/pdf.js:60:21","    at respond (/var/task/node_modules/html-pdf/lib/pdf.js:141:14)","    at ChildProcess.onError (/var/task/node_modules/html-pdf/lib/pdf.js:149:46)","    at ChildProcess.emit (node:events:527:28)","    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)","    at onErrorNT (node:internal/child_process:478:16)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]}
> Unknown application error occurred
> ```

I also still get the same issue here...

**Comment by RobzLegz** [comment]
@eg-delacruz I didn't fix it, decided to write a python api just for mailing pdfs.

**Comment by banjoadeola** [comment]
This issue hasn't been fixed.

Error: spawn /usr/src/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /usr/src/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
  path: '/usr/src/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
  spawnargs: [
    '--local-url-access=false',
    '/usr/src/app/node_modules/html-pdf/lib/scripts/pdf_a4_portrait.js'
  ]
}
