### ISSUE TITLE
Add support for `fast-glob`

### ISSUE THREAD

**Issue by styfle** [zeit/node-file-trace#55]
The `fast-glob` package depends on `@nodelib/fs.stat` but the trace fails to pick up this dependency.

It finds these two just fine:

```
fast-glob/out/providers/stream.js
fast-glob/out/providers/sync.js
```

Here's the contents of `sync.js` which clearly requires fs.stat:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fsStat = require("@nodelib/fs.stat");
const fsWalk = require("@nodelib/fs.walk");
const reader_1 = require("./reader");
class ReaderSync extends reader_1.default {
    constructor() {
        super(...arguments);
        this._walkSync = fsWalk.walkSync;
        this._statSync = fsStat.statSync;
    }
    dynamic(root, options) {
        return this._walkSync(root, options);
    }
    static(patterns, options) {
        const entries = [];
        for (const pattern of patterns) {
            const filepath = this._getFullEntryPath(pattern);
            const entry = this._getEntry(filepath, pattern, options);
            if (entry === null || !options.entryFilter(entry)) {
                continue;
            }
            entries.push(entry);
        }
        return entries;
    }
    _getEntry(filepath, pattern, options) {
        try {
            const stats = this._getStat(filepath);
            return this._makeEntry(stats, pattern);
        }
        catch (error) {
            if (options.errorFilter(error)) {
                return null;
            }
            throw error;
        }
    }
    _getStat(filepath) {
        return this._statSync(filepath, this._fsStatSettings);
    }
}
exports.default = ReaderSync;
```

cc @williamli @Timer

**Comment by AryanJ-NYC** [comment]
Related to: https://github.com/zeit/now/issues/3115

**Comment by elvenking** [comment]
Is there any progress ?

**Comment by stolinski** [comment]
Hitting this same issue via https://github.com/accounts-js/accounts using `graphql-toolkit`. Since it's another package using `graphql-toolkit` and not a direct dependency, I'm not sure I'm able to use @elvenking 's fix.

**Comment by stolinski** [comment]
Doesn't look like there is any progress on https://github.com/acornjs/acorn-stage3/issues/4 are there any work arounds for this?

**Comment by styfle** [comment]
You can use [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to define an alternative dependency

**Comment by stolinski** [comment]
@styfle what should I have as a resolution if this is a bug with acorn-stage3?

**Comment by styfle** [comment]
Acorn is used by node-file-trace for parsing JS source files.

This prevents `fast-glob` from being parsed properly. Normally this isn't a problem for most ZEIT Now builds because globbing is typically used a build time, not runtime (and NFT is not used during build time, only runtime).

However, it looks like graphql uses globbing at runtime to detect files.

One workaround as @elvenking [mentioned](https://github.com/zeit/now/issues/3115#issuecomment-554660513) is to change the dependency in `package.json`.

If you can't change a dependency in `package.json` because its a transitive dependency, you can use [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to force a different version of `fast-glob` to be resolved. I just published a [fork](https://github.com/styfle/fast-glob/blob/master/package.json) with a minor change to their source code. It should work if you add the following property to your `package.json`:

```json
{
  "resolutions": {
    "fast-glob": "https://files-5653q5abb.now.sh"
  }
}
```

Then delete `yarn.lock` and run `yarn install` again.

**Comment by stolinski** [comment]
Works perfectly with the `"fast-glob": "https://files-5653q5abb.now.sh"` Thanks @styfle

**Comment by leerob** [comment]
I'm not sure if this is fixed or I'm missing something. I see that a test case was added for fast-glob here https://github.com/zeit/node-file-trace/pull/99 and that it was released with `@now/next` here https://github.com/zeit/now/pull/3613. 

I figured I should just be able to rebuild my application and it would work, but it did not. I'm trying to add an API route that uses `globby`. Here's the error I get.

```
2020-01-19T20:12:31.794Z	23d82f65-69da-474c-a015-6f51d9e4eda2	ERROR	Error: Cannot find module '@nodelib/fs.stat'
Require stack:
- /var/task/node_modules/fast-glob/out/readers/stream.js
- /var/task/node_modules/fast-glob/out/providers/async.js
- /var/task/node_modules/fast-glob/out/index.js
- /var/task/node_modules/globby/index.js
- /var/task/.next/serverless/pages/api/sitemap.js
- /var/task/now__launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/task/node_modules/fast-glob/out/readers/stream.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/fast-glob/out/readers/stream.js',
    '/var/task/node_modules/fast-glob/out/providers/async.js',
    '/var/task/node_modules/fast-glob/out/index.js',
    '/var/task/node_modules/globby/index.js',
    '/var/task/.next/serverless/pages/api/sitemap.js',
    '/var/task/now__launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}END RequestId: 23d82f65-69da-474c-a015-6f51d9e4eda2
```

Here's an example of it throwing a 500: https://leerob-m0m4dgj6e.now.sh/api/sitemap

Thoughts? Am I missing something?

**Comment by styfle** [comment]
The fix was released to the canary channel. 

‘’’
npm i -g now@canary
‘’’

**Comment by leerob** [comment]
Ah, that makes sense. Re-deploying via the dashboard must use the stable version. Thanks!
