### ISSUE TITLE
FS operations from compiled TypeScript import are ignored

### ISSUE THREAD

**Issue by jkrems** [zeit/node-file-trace#76]
If a third-party module was compiled from TypeScript (I assume the same is true for babel as well), the resulting code looks like this (simplified):

```js
// Original:
import fs from 'fs';
fs.readFileSync('/path/to/file');

// Actual code:
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
const fs_1 = __importDefault(require("fs"));
fs_1.default.readFileSync('/path/to/file');
```

Afaict this causes `node-file-trace` to miss these file system operations, omitting the files from the build output.

**Comment by styfle** [comment]
Are you using an absolute path or is that just an example?

Does it work if you use a file relative to `__dirname`?

```js
fs.readFileSync(path.join(__dirname, 'path', 'to', file'));
```

**Comment by jkrems** [comment]
I'm pretty sure the issue is that it never associates `fs_1.default.readFileSync` with the `FS_FN` stub. In my original tests I was using `path.resolve` which I verified works when using `require` from the same file (because `require` doesn't cause the `__importDefault` wrapper).

The exact same Typescript source file works when rewritten like this:

```ts
// Original (and actual code because require doesn't get transformed)
const fs = require('fs');
fs.readFileSync('/path/to/file');
```

**Comment by jkrems** [comment]
Hm, can not reproduce using a simpler example from within this repo. Possible that I thought this was the issue when I ran into inclusions based on package boundary. Will close for now until I have a reliable repro.

**Comment by jkrems** [comment]
```js
'use strict';

var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
{
  // Using ts-style / babel-style import
  // In babel, __importDefault is called _interopRequireDefault
  const fs_1 = __importDefault(require("fs"));
  const path_1 = __importDefault(require("path"));
  const filename = path_1.default.resolve('readme.md');
  const content = fs_1.default.readFileSync(filename);
  console.log(content);
}

{
  // Using require
  const fs = require('fs');
  const path = require('path');

  const filename = path.resolve('yarn.lock');
  const content = fs.readFileSync(filename);
  console.log(content);
}
```

Putting the file above into a checkout of this library, this command shows the problem:

```bash
$ node src/cli.js print ts-import.js
FILELIST:
ts-import.js
yarn.lock
```

It should print both `yarn.lock` and `readme.md` but it only finds the one referenced from the direct require code path.

**Comment by jkrems** [comment]
Created a branch with failing tests for these: https://github.com/zeit/node-file-trace/compare/master...jkrems:babel-ts-trace?expand=1
