### ISSUE TITLE
Trace stops at `.mjs` files

### ISSUE THREAD

**Issue by jkrems** [zeit/node-file-trace#80]
With the advent of `--experimental-modules` getting unflagged, it may be good to support tracing through `.mjs` files. It looks like right now it doesn't even try to parse them?

**Comment by styfle** [comment]
There is some conditions checking for `.mjs` extension but I don't see any tests 🤔 

Perhaps support for `.mjs` was never finished.

https://github.com/zeit/node-file-trace/blob/21019e249d20d55c22d94e183079622b0f4a85f8/src/node-file-trace.js#L212

**Comment by guybedford** [comment]
`.mjs` files should definitely be traced fine by this project, although note that `import './x'` will not automatically load `x.mjs` in extension searching. Is there a test case for this you can share?

**Comment by jkrems** [comment]
I think I backed out those changes. IIRC it was a "simple" matter of having an import statement that used `.mjs`.

**Comment by guybedford** [comment]
Ok, I did try adding a simple unit test with a `import './dep.mjs'` and another deep `.mjs` dependency and it worked out fine for me here with the setup in this project repo.

Perhaps you weren't checking `esmFiles`, which is a separate output?

**Comment by guybedford** [comment]
*esmFileList

**Comment by jkrems** [comment]
Since there's no easy repro (and a simple case wasn't enough), let's close this issue. This can always be opened back up again if somebody else runs into an issue there.
